const initialsNotes = [
  {
    id: 1,
    name: 'JS Project',
    created: 'July 31, 2023',
    category: 'Task',
    content: 'I must create a note app on JS for Radency intern program',
    dates: ['01/08/2023'],
    archived: false,
  },
  {
    id: 2,
    name: 'Not a bad hint to speed up work',
    created: 'July 31, 2023',
    category: 'Idea',
    content: 'I can use my previous projects to do faster all my tasks ',
    dates: ['01/08/2023'],
    archived: false,
  },
  {
    id: 3,
    name: 'React Project',
    created: 'July 31, 2023',
    category: 'Task',
    content: 'I must create a project on React for Radency intern program',
    dates: ['04/08/2023'],
    archived: false,
  },
  {
    id: 4,
    name: 'Node Project',
    created: 'July 31, 2023',
    category: 'Task',
    content: 'I must create a project on Node.js for Radency intern program',
    dates: ['07/08/2023'],
    archived: false,
  },

  {
    id: 5,
    name: 'England PL',
    created: 'July 31, 2023',
    category: 'Random Thought',
    content: "The English Premier League starts on August 11 - don't forget to watch it",
    dates: ['11/08/2023'],
    archived: false,
  },
  {
    id: 6,
    name: 'Hobby',
    created: 'July 31, 2023',
    category: 'Random Thought',
    content: 'I want to go fishing',
    dates: ['12/08/2023', '15/08/2023'],
    archived: true,
  },
  {
    id: 7,
    name: 'My plan',
    created: 'July 31, 2023',
    category: 'Idea',
    content: 'If I done my JS-project faster then I will definitely go fishing',
    dates: [],
    archived: false,
  },
];

export default initialsNotes;
